[package]
name = "gamebot"
authors = ["Ivan Temchenko <https://github.com/35359595>"]
description = "Discord words game bot"
license = "EUPL-v1.3"
version = "0.1.0"
edition = "2021"

[dependencies]
discord = { git = "https://github.com/SpaceManiac/discord-rs" }
sqlite = "^0.31"
rand = "^0.8"
